-- CREATE TABLES FOR STARTSMART SCHEMA

-- 1. Manager Table
CREATE TABLE IF NOT EXISTS startsmart.ss_manager (
    emp_code BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. Mentor Table
CREATE TABLE IF NOT EXISTS startsmart.ss_mentor (
    emp_code BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Rename columns if they still use the old _code suffix
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='startsmart' AND table_name='ss_cfl_assignment' AND column_name='cfl_emp_code') THEN
        ALTER TABLE startsmart.ss_cfl_assignment RENAME COLUMN cfl_emp_code TO cfl_emp_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='startsmart' AND table_name='ss_cfl_assignment' AND column_name='hr_emp_code') THEN
        ALTER TABLE startsmart.ss_cfl_assignment RENAME COLUMN hr_emp_code TO hr_emp_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='startsmart' AND table_name='ss_cfl_assignment' AND column_name='manager_emp_code') THEN
        ALTER TABLE startsmart.ss_cfl_assignment RENAME COLUMN manager_emp_code TO manager_emp_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='startsmart' AND table_name='ss_cfl_assignment' AND column_name='mentor_emp_code') THEN
        ALTER TABLE startsmart.ss_cfl_assignment RENAME COLUMN mentor_emp_code TO mentor_emp_id;
    END IF;
END $$;

-- 3. CFL Assignment Table
CREATE TABLE IF NOT EXISTS startsmart.ss_cfl_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    hr_emp_id BIGINT NOT NULL,
    manager_emp_id BIGINT,
    mentor_emp_id BIGINT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (manager_emp_id) REFERENCES startsmart.ss_manager(emp_code),
    FOREIGN KEY (mentor_emp_id) REFERENCES startsmart.ss_mentor(emp_code)
);

-- 4. CFL Profile Table
CREATE TABLE IF NOT EXISTS startsmart.ss_cfl_profile (
    cfl_emp_id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255),
    department VARCHAR(255),
    business_unit VARCHAR(255),
    goal_progress INT DEFAULT 0
);
