CREATE TABLE IF NOT EXISTS startsmart.ss_goal_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INT NOT NULL,
    cycle_name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_goal_stage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_code VARCHAR(20) NOT NULL UNIQUE,
    stage_name VARCHAR(50) NOT NULL,
    sequence_no INT NOT NULL UNIQUE,
    duration_days INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS startsmart.ss_goal_workflow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    stage_id BIGINT NOT NULL,
    cfl_emp_id BIGINT NOT NULL,
    hr_emp_id BIGINT NOT NULL,
    manager_emp_id BIGINT NOT NULL,
    initial_meeting_id BIGINT,
    review_meeting_id BIGINT,
    previous_stage_id BIGINT,
    status VARCHAR(40) NOT NULL,
    meeting_completed_at TIMESTAMP,
    unlocked_at TIMESTAMP,
    goal_submitted_at TIMESTAMP,
    review_completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_goal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL UNIQUE,
    cycle_id BIGINT NOT NULL,
    stage_id BIGINT NOT NULL,
    cfl_emp_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    target_date DATE,
    weightage DECIMAL(5,2) NOT NULL,
    progress_pct DECIMAL(5,2) DEFAULT 0 NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_progress CHECK (progress_pct BETWEEN 0 AND 100),
    CONSTRAINT chk_weightage CHECK (weightage BETWEEN 0 AND 100)
);

CREATE TABLE IF NOT EXISTS startsmart.ss_goal_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL,
    reviewer_emp_id BIGINT NOT NULL,
    reviewer_role VARCHAR(30) NOT NULL,
    action VARCHAR(30) NOT NULL,
    comment TEXT,
    reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
