CREATE TABLE IF NOT EXISTS startsmart.ss_meeting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    agenda TEXT,
    scheduled_at TIMESTAMP NOT NULL,
    duration_minutes INT,
    mode VARCHAR(20) NOT NULL,
    meeting_link VARCHAR(1000),
    external_meeting_id VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    completed_at TIMESTAMP,
    created_by BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_meeting_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    emp_id BIGINT NOT NULL,
    participant_role VARCHAR(30) NOT NULL,
    response_status VARCHAR(30) NOT NULL,
    joined_at TIMESTAMP
);
