CREATE TABLE IF NOT EXISTS startsmart.ss_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT,
    from_emp_id BIGINT NOT NULL,
    to_emp_id BIGINT NOT NULL,
    feedback_type VARCHAR(40) NOT NULL,
    rating DECIMAL(3,1),
    comments TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
