CREATE TABLE IF NOT EXISTS startsmart.ss_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT,
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
