CREATE TABLE IF NOT EXISTS startsmart.ss_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name VARCHAR(150) NOT NULL UNIQUE,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_cfl_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    proficiency VARCHAR(30),
    experience_years DECIMAL(4,1),
    CONSTRAINT uq_cfl_skill UNIQUE(cfl_emp_id, skill_id)
);
