CREATE TABLE IF NOT EXISTS startsmart.ss_performance_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    cycle_id BIGINT NOT NULL,
    performance_rating INT NOT NULL,
    potential_rating INT NOT NULL,
    talent_level VARCHAR(50),
    overall_comment TEXT,
    strengths TEXT,
    areas_of_improvement TEXT,
    status VARCHAR(30) NOT NULL,
    submitted_at TIMESTAMP
);
