CREATE TABLE IF NOT EXISTS startsmart.ss_competency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_competency_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL,
    competency_id BIGINT NOT NULL,
    rating INT NOT NULL,
    comment TEXT NOT NULL,
    CONSTRAINT uq_assess_competency UNIQUE(assessment_id, competency_id)
);
