CREATE TABLE IF NOT EXISTS startsmart.ss_career_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    suggested_role_id BIGINT,
    skill_gap TEXT,
    backup_allowed BOOLEAN,
    backup_for_emp_id BIGINT,
    project_id BIGINT,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_probation_evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    due_date DATE NOT NULL,
    manager_emp_id BIGINT NOT NULL,
    manager_rating INT,
    manager_feedback TEXT,
    manager_submitted_at TIMESTAMP,
    hr_status VARCHAR(30) NOT NULL,
    hr_comment TEXT,
    hr_action_at TIMESTAMP,
    final_status VARCHAR(30)
);
