CREATE TABLE IF NOT EXISTS startsmart.ss_recognition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_emp_id BIGINT NOT NULL,
    to_emp_id BIGINT NOT NULL,
    recognition_type VARCHAR(30) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS startsmart.ss_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cfl_emp_id BIGINT NOT NULL,
    memory_year INT NOT NULL,
    title VARCHAR(255),
    description TEXT,
    media_type VARCHAR(20) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
